# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
#
# http://go.microsoft.com/fwlink/?LinkId=320437

# Builds the library for Windows Desktop.

schedules:
- cron: "30 5 * * *"
  displayName: 'Nightly build'
  branches:
    include:
    - main

# GitHub Actions handles MSBuild for CI/PR
trigger: none
pr:
  branches:
    include:
    - main
  paths:
    include:
    - '.azuredevops/pipelines/DXUT-GitHub.yml'

resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main

name: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

variables:
  Codeql.Enabled: false

pool:
  vmImage: windows-2019

jobs:
- job: DESKTOP_BUILD
  displayName: 'Win32 Desktop'
  timeoutInMinutes: 60
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: VSBuild@1
    displayName: Build solution DXUT_2019_Win10.sln 32dbg
    inputs:
      solution: DXUT_2019_Win10.sln
      msbuildArgs: /p:PreferredToolArchitecture=x64
      platform: Win32
      configuration: Debug
  - task: VSBuild@1
    displayName: Build solution DXUT_2019_Win10.sln 32rel
    inputs:
      solution: DXUT_2019_Win10.sln
      msbuildArgs: /p:PreferredToolArchitecture=x64
      platform: Win32
      configuration: Release
  - task: VSBuild@1
    displayName: Build solution DXUT_2019_Win10.sln 64dbg
    inputs:
      solution: DXUT_2019_Win10.sln
      msbuildArgs: /p:PreferredToolArchitecture=x64
      platform: x64
      configuration: Debug
  - task: VSBuild@1
    displayName: Build solution DXUT_2019_Win10.sln 64rel
    inputs:
      solution: DXUT_2019_Win10.sln
      msbuildArgs: /p:PreferredToolArchitecture=x64
      platform: x64
      configuration: Release

- job: DESKTOP_BUILD_SPECTRE
  displayName: 'Win32 Desktop (Spectre-mitigated)'
  timeoutInMinutes: 60
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: VSBuild@1
    displayName: Build solution DXUT_2019_Win10.sln 32dbg
    inputs:
      solution: DXUT_2019_Win10.sln
      msbuildArgs: /p:PreferredToolArchitecture=x64 /p:SpectreMitigation=Spectre
      platform: Win32
      configuration: Debug
  - task: VSBuild@1
    displayName: Build solution DXUT_2019_Win10.sln 32rel
    inputs:
      solution: DXUT_2019_Win10.sln
      msbuildArgs: /p:PreferredToolArchitecture=x64 /p:SpectreMitigation=Spectre
      platform: Win32
      configuration: Release
  - task: VSBuild@1
    displayName: Build solution DXUT_2019_Win10.sln 64dbg
    inputs:
      solution: DXUT_2019_Win10.sln
      msbuildArgs: /p:PreferredToolArchitecture=x64 /p:SpectreMitigation=Spectre
      platform: x64
      configuration: Debug
  - task: VSBuild@1
    displayName: Build solution DXUT_2019_Win10.sln 64rel
    inputs:
      solution: DXUT_2019_Win10.sln
      msbuildArgs: /p:PreferredToolArchitecture=x64 /p:SpectreMitigation=Spectre
      platform: x64
      configuration: Release
